### PR TITLE
Added copy to clipboard, better bootstrap checkboxes and small fixes in HTML 

### PR DESCRIPTION
**Pull request by max-programming**
Hi again! I am just feeling very excited to add as more as I can to this project. It's a really awesome project which I have loved!
## 1.
So in this one, I added the functionality of copying the markdown with a click
image

## 2.
I made the default checkboxes the custom checkboxes by Bootstrap
Before: 
image
After:
image

And fixed some small issues in the HTML like the `<link>` tags which were closing and not self closing.

I hope these changes are good and acceptable 😊

### CODE REVIEW

**Comment by arturssmirnovs** [comment]
Some body is one fire .. Good job and thanks, you are awesome..
I will review your commits tomorrow morning and merge them in to master(main) :)

**Comment by max-programming** [comment]
No problem. I just felt that it needs more features so I thought of adding them as much as I can. Let me know if you want to change something 😊. 

I still have lots of ideas in my mind. Hopefully I will try to implement them in the next weekend.

**Review by arturssmirnovs — APPROVED** [review]

**Comment by arturssmirnovs** [comment]
Thanks, i merged your commits.. 
Yes, think it still could do some improvements.. Maybe i will think what else could be made and add issues so we have full overview of some other new features.. 

Good job and thanks again!

**Comment by max-programming** [comment]
@arturssmirnovs Can we save the Vue.js file and Vue markdown file from the CDN and add it to our `js` folder? Because if the internet connection is slow, it takes some time, shows the hidden alert, and also shows the `{{ source }}` because the Vue files are not loaded

**Comment by arturssmirnovs** [comment]
Sure, feel free to improve on that as well..

**Comment by max-programming** [comment]
Okay then, in the next commit. I have thought something pretty exciting for the next one. Working on it

Should I disable the textarea? Because no one should edit it. Is it ok?

**Comment by arturssmirnovs** [comment]
I had idea that person still can edit it after generated information.. 

So then generate basic information and then editing textarea they can improve it even more.. 

I added you as collaborator, so you can merge your requests your self :) You have earned it.. 
Just some major features let's still discuss maybe..

**Comment by max-programming** [comment]
Oh that's a very good opportunity for me. I will learn so many things. Thanks a lot for adding me. Maybe we should try this feature by GitHub, so whatever idea I get, I will put it right over there.
image
P.S. I don't know how to use this feature.

**Comment by arturssmirnovs** [comment]
Let's use Issues better.. as this project is not so big.. and just put proper label to issue.. then we can discuss issue / improvement there... 👍

**Comment by max-programming** [comment]
NP. We'll use issues. Also, take a look at the PR #14 where I have talked about some problems

**Comment by max-programming** [comment]
@arturssmirnovs Should I add hacktoberfest-accepted label to my PR? What does it do?

**Comment by arturssmirnovs** [comment]
@max-programming Not sure if you have heard about https://hacktoberfest.digitalocean.com/ #hacktoberfest ,,
You can register on that website and if you do 4 PR you will get free T-shirt and stickers.. i think first 75k gets it..

and @fx2000 according to digitalocean that label does nothing if PR is accepted and marged... See info:
_Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it._

**Comment by max-programming** [comment]
I know about Hacktoberfest @arturssmirnovs . I found this repo with the help of the hacktoberfest topic 😂.
But I wasn't knowing what the label on the PR does. 
So the PR will **maybe be counted** if the maintainer accepts and merges it right? Even if the hacktoberfest label is not on the PR.

I also made a video mentioning your repository, check it out [here](https://youtu.be/RjxDDhMqwrM)
I got it. Thanks for the info: 
image

**Comment by arturssmirnovs** [comment]
Yes, it just has to be merged, so no worries.. 

Here is another person who made video about this generator: https://www.youtube.com/watch?v=KhGWbt1dAKQ&t=384s

Thanks mate, again, you are awesome!

**Comment by max-programming** [comment]
Thanks to you for making this awesome project! I learnt many things!

**Pull request merged**
