### PR TITLE
Added CodeSandbox to Socials

### PR DESCRIPTION
**Pull request by max-programming**
I added CodeSandbox to the Socials section and also I changed the `v-bind:` to `:` and `v-on` to `@`. As Vue.js has evolved, I changed these so the code looks much neater. Let me know if you have any issues

### CODE REVIEW

**Comment by arturssmirnovs** [comment]
Thanks 👍

**Comment by max-programming** [comment]
@arturssmirnovs How if I also add the icons to the labels of the input fields. I will create a new PR. (If you want)
Before the labels
image

**Comment by arturssmirnovs** [comment]
yup, why not, could be nice small improvement..

**Comment by max-programming** [comment]
> yup, why not, could be nice small improvement..

Okay. I will do it tomorrow

**Pull request merged**
